acari:
  mongo:
    connectionString: mongo
    landingDatabase: landing

server:
  ssl:
    key-store: classpath:mongodb-client.jks
    key-password: 654321
    key-store-type: JKS
    key-alias: mykey
    key-store-provider: SUN
    enabled: true
  port: 8080
