acari:
  mongo:
    connectionString: mongodb://mongo:27017
    landingDatabase: landing

server:
  ssl:
    key-store: keystore.p12
    key-password: 123456 #AMAZING! That's my luggage password!!
    key-store-type: PKCS12
    key-alias: acarilanding
  port: 8811
