acari:
  mongo:
    connectionString: mongodb://mongo:27017/admin?authMechanism=MONGODB-X509&ssl=true
    landingDatabase: landing

javax:
  net:
    ssl:
      trustStore: /app/mongodb-client.jks
      trustStorePassword: 123456 #That's amazing! I got the same combination on my luggage!
      keystore: /app/mongodb-client.jks
      keystorePassword: 123456