version: "3"
services:
  web-service:
    build: ./web-service
    image: alexsimons/acari-web-service:1.1.4
    depends_on:
      - mongo
    ports:
      - "443:8080"
      - "7896:7896"
  mongo:
      image: alexsimons/mongo-ssl:0.0.2
      build:
        context: ./mongo
      volumes:
        - "./dataDump/:/data/db"
      ports:
        - "27017:27017"