version: "3"
services:
  web-content:
    build:
      dockerfile: Dockerfile-dev
      context: ./web-content
    image: alexsimons/acari-web-content
    ports:
      - "3000:3000"
    volumes:
      - ./web-content:/app
  web-service:
    build: ./web-service
    image: alexsimons/acari-web-service
    ports:
      - "8989:8989"
      - "7896:7896"
  mongo:
    image: alexsimons/mongo-ssl:0.0.2
    build:
      context: ./mongo
    volumes:
      - "./dataDump/:/data/db"

