version: "3"
services:
  web-content:
    build:
      dockerfile: Dockerfile-install
      context: ./web-content
    image: alexsimons/nodeinstall:9.2.0
    volumes:
      - "./:/app"
    entrypoint:
      - /bin/bash
    command:
      - "-c"
      - "cd web-content; npm run watch"
    ports:
      - "3000:3000"
  web-service:
    build: ./web-service
    image: alexsimons/acari-web-service
    ports:
      - "8989:8989"
      - "7896:7896"
  mongo:
    image: alexsimons/mongo-ssl:0.0.2
    build:
      context: ./mongo
    volumes:
      - "./dataDump/:/data/db"
    ports:
      - "27017:27017"

